apiVersion: v1
kind: ConfigMap

metadata:
  name: hospital-configmap

data:
  MONGO_URI: "mongodb://mongodb-service:27017/hospital_management"
  PORT: "5000"
  NODE_ENV: "production"

---
apiVersion: v1
kind: Secret

metadata:
  name: hospital-secret

type: Opaque

stringData:
  SESSION_SECRET: "hospital123"
  JWT_SECRET: "hospitaljwt123"
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "admin123"
