apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hospital-app

  template:
    metadata:
      labels:
        app: hospital-app

    spec:
      containers:
        - name: hospital-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          ports:
            - containerPort: 5000

          env:
            - name: MONGO_URI
              value: "{{ .Values.env.MONGO_URI }}"
            - name: PORT
              value: "{{ .Values.env.PORT }}"
            - name: NODE_ENV
              value: "{{ .Values.env.NODE_ENV }}"
